apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-hello-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-hello-app
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: node-hello-app
    spec:
      containers:
      - name: hello-app
        image: tharindub/node-hello-app:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 100m