apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-hello-app

spec:
  replicas: 2
  selector:
    matchLables:
      app: node-hello-app
  template:
    metadata:
      labels:
       app: node-hello-app
    spec:
      containers:
      - 
        name: hello app
        image: tharindub/node-hello-app:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 100m
