# apiVersion: v1
# kind: Service
# metadata:
#   name: node-hello-app-service
# spec:
#   ports:
#     - port: 80
#       targetPort: 8080
#   selector:
#     app: node-hello-app

apiVersion: v1
kind: Service
metadata:
  name: node-hello-app-service
spec:
  type: NodePort
  selector:
    app: node-hello-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30007