apiVersion: v1
kind: Service
metadata:
  name: node-hello-app-service
spec:
  type: NodePort
  selector:
    app: webapp
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 8080
