name: Build and deploy

on:
  push:
    branches:
      - main

env:
  DEPLOYMENT_NAME: node-hello-app
  PROJECT_ID: ${{ secrets.GKA_PROJECT }}
  GKE_CLUSTER: cluster-1-tharindu
  GKE_ZONE: us-central1-c


jobs:
  setup-build-publish:
    name: Setup build and setup-build-publish
    runs-on: ubuntu-latest

    steps:
      - run: echo "Build started "
      -
        name: Checkout repository
        uses: actions/checkout@v3
      - run: echo "Project repository has been clonde to runnner(ubuntu)"

      #Login to docker hub
      -
        name: Login to docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      #Build and push to docker hub

      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{env.DEPLOYMENT_NAME}}:latest
  
  deploy:
    needs: setup-build-publish
    name: deploy to GCP
    runs-on: ubuntu-latest
    steps:
      - 
        run: echo "Deplyment started"
    #Authencate GCP
      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
        run: echo "Logged in to GCP"


      

      

    